export const PAGES = Object.freeze({
  INIT_APP: '@pages/INIT_APP',
  REQUEST_HOME: '@pages/REQUEST_HOME_PAGE',
  REQUEST_MATCH: '@pages/REQUEST_MATCH_PAGE',
  SUCCESS_HOME: '@pages/SUCCESS_HOME_PAGE',
  SUCCESS_MATCH: '@pages/SUCCESS_HOME_PAGE',
});