export const RIOT = Object.freeze({
  PATCH_REQUEST: '@riot/PATCH_REQUEST',
  PATCH_SUCCESS: '@riot/PATCH_SUCCESS',
  PATCH_FAILURE: '@riot/PATCH_FAILURE',
  RUNES_REQUEST: '@riot/RUNES_REQUEST',
  RUNES_SUCCESS: '@riot/RUNES_SUCCESS',
  RUNES_FAILURE: '@riot/RUNES_FAILURE',
});