export const GAME = Object.freeze({
  INIT_REQUEST: '@game/INIT_GAME_LOAD_REQUEST',
  INIT_SUCCESS: '@game/INIT_GAME_LOAD_SUCCESS',
  INIT_FAILURE: '@game/INIT_GAME_LOAD_FAILURE',
  UPDATE_REQUEST: '@game/UPDATE_GAME_LOAD_REQUEST',
  UPDATE_SUCCESS: '@game/UPDATE_GAME_LOAD_SUCCESS',
  UPDATE_FAILURE: '@game/UPDATE_GAME_LOAD_FAILURE',
  CHANGE_GAME: '@game/CHANGE_ACTIVE_GAME',
});